#Configuration file for PhishDetector

#Data and Test Matrix Configurations
root_dir:                       ../broScripts/output
sender_profile_percentage:      0.1
data_matrix_percentage:         0.2
test_matrix_percentage:         0.7
use_name_in_from:               0

#Model Training and Classification Settings
weights:
    positive:                   0.02
    negative:                   1.0
model_path_out:                 model.plk
result_path_out:                output
results_size:                   20
emails_threshold:               1000
batch_threading_size:           100
offline:                        1
detectors:
    DateTimezoneDetector:       1
    MessageIdFormatDetector:    1
    MessageIdDomainDetector:    1
    ContentTypeDetector:        1
    OrderOfHeaderDetector:      1
    XMailerDetector:            1
    ReceivedHeadersDetector:    1
    DateFormatDetector:         1

#Parallel Settings
parallel:                       0
num_threads:                    5

#Memory Logging Settings
memlog_gen_features_frequency:  10
memlog_classify_frequency:      1

#Do not modify unless you are certain what you are doing
regular_filename:               legit_emails.log
phish_filename:                 phish_emails.log

#Progress Configurations
logging_interval:               10
