#Configuration file for PhishDetector

#Data and Test Matrix Configurations
root_dir:                       ../broScripts/output
use_name_in_from:               1

#Config for splits
use_percentage:                 1

#if use_percentage = 1
sender_profile_percentage:      0.1
data_matrix_percentage:         0.2
test_matrix_percentage:         0.7

#if use_percentage = 0
#Format: Month Day Year
#interval = [start, end)
sender_profile_start_time:      "March 5 2014"
sender_profile_end_time:        "March 9 2014"
train_start_time:               "March 9 2014"
train_end_time:                 "September 27 2014"
test_start_time:                "September 27 2014"
test_end_time:                  "February 7 2015"

#Model Training and Classification Settings
weights:
    positive:                   0.02
    negative:                   1.0
model_path_out:                 model.plk
result_path_out:                output
results_size:                   100
emails_threshold:               1000
batch_threading_size:           100
offline:                        1
detectors:
    DateTimezoneDetector:       1
    MessageIdFormatDetector:    1
    MessageIdDomainDetector:    1
    ContentTypeDetector:        1
    OrderOfHeaderDetector:      1
    XMailerDetector:            1
    ReceivedHeadersDetector:    1
    DateFormatDetector:         1
    ProvidersDetector:          1

#Parallel Settings
parallel:                       0
num_threads:                    5

#Memory Logging Settings
memlog_gen_features_frequency:  10
memlog_classify_frequency:      1

#Do not modify unless you are certain what you are doing
regular_filename:               legit_emails.log
phish_filename:                 phish_emails.log

#Progress Configurations
logging_interval:               10

# Filter Inputs
senders:                        sender_targets.txt
recipients:                     recipient_targets.txt
